src/EPR.RegulatorService.Frontend.Web/ViewModels/ApprovedPersonListPage/OrganisationUsersModel.cs
namespace EPR.RegulatorService.Frontend.Web.ViewModels.ApprovedPersonListPage;

using System.ComponentModel.DataAnnotations;

using Core.Models;

public class OrganisationUsersModel
{
    public Guid ExternalOrganisationId { get; set; }

    public List<OrganisationUser>? OrganisationUsers { get; set; }

    [Required(ErrorMessage = "SelectNominatedApprovedPerson")]
    public Guid? NewApprovedUserId { get; set; }
}

src/EPR.RegulatorService.Frontend.Web/ViewModels/RemoveApprovedUser/ApprovedUserToRemoveViewModel.cs
using System.Diagnostics.CodeAnalysis;

namespace EPR.RegulatorService.Frontend.Web.ViewModels.RemoveApprovedUser;

[ExcludeFromCodeCoverage]
public class ApprovedUserToRemoveViewModel
{
    public Guid ConnExternalId { get; set; }
    public Guid OrganisationId { get; set; }

    public bool? NominationDecision { get; set; }

    public Guid PromotedPersonExternalId { get; set; }

}

src/EPR.RegulatorService.Frontend.Web/ViewModels/RemoveApprovedUser/RemovedNominatedUserViewModel.cs
using System.Diagnostics.CodeAnalysis;

namespace EPR.RegulatorService.Frontend.Web.ViewModels.RemoveApprovedUser;

[ExcludeFromCodeCoverage]
public class RemovedNominatedUserViewModel
{
    public string PromotedUserName { get; set; }

    public string RemovedUserName { get; set; }

    public string OrganisationName { get; set; }
}

src/EPR.RegulatorService.Frontend.Web/Controllers/RemoveApprovedUser/RemoveApprovedUserController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.FeatureManagement.Mvc;
using EPR.RegulatorService.Frontend.Web.Sessions;
using EPR.RegulatorService.Frontend.Web.ViewModels.ApprovedPersonListPage;
using EPR.RegulatorService.Frontend.Web.ViewModels.RemoveApprovedUser;
using EPR.RegulatorService.Frontend.Web.Configs;
using EPR.RegulatorService.Frontend.Core.Sessions;
using EPR.RegulatorService.Frontend.Web.Constants;
using EPR.RegulatorService.Frontend.Core.Services;
using EPR.RegulatorService.Frontend.Core.Models;

namespace EPR.RegulatorService.Frontend.Web.Controllers.RemoveApprovedUser;

[FeatureGate(FeatureFlags.ManageApprovedUsers)]
public class RemoveApprovedUserController : RegulatorSessionBaseController
{
    private readonly IFacadeService _facadeService;
    public RemoveApprovedUserController(ISessionManager<JourneySession> sessionManager,
        IConfiguration configuration,
        IFacadeService facadeService) : base(sessionManager, configuration)
    {
        _facadeService = facadeService;
    }

    [HttpGet]
    [Route(PagePath.RemoveApprovedUserConfirmationPage)]
    public async Task<IActionResult> Confirm(string userName, string organisationName, Guid connExternalId, Guid organisationId)
    {
        var session = await _sessionManager.GetSessionAsync(HttpContext.Session) ?? new();

        if (connExternalId != Guid.Empty
            && organisationId != Guid.Empty
            && !string.IsNullOrWhiteSpace(organisationName))
        {
            session.AddRemoveApprovedUserSession = new AddRemoveApprovedUserSession
            {
                UserNameToRemove = userName,
                ConnExternalId = connExternalId,
                NominationDecision = null,
                OrganisationName = organisationName,
                ExternalOrganisationId = organisationId,
                CurrentApprovedUserEmail = session.AddRemoveApprovedUserSession.CurrentApprovedUserEmail
            };
            await SaveSession(session);
        }

        await AddCurrentPageAndSaveSession(session, PagePath.RemoveApprovedUserConfirmationPage);
        SetBackLink(session, PagePath.RemoveApprovedUserConfirmationPage);

        return View(session.AddRemoveApprovedUserSession);
    }

    [HttpGet]
    [Route(PagePath.NominationDecision)]
    public async Task<IActionResult> NominationDecision()
    {
        var session = await _sessionManager.GetSessionAsync(HttpContext.Session) ?? new();

        await AddCurrentPageAndSaveSession(session, PagePath.NominationDecision);
        SetBackLink(session, PagePath.NominationDecision);


        return View(session.AddRemoveApprovedUserSession);
    }

    [HttpPost]
    [Route(PagePath.NominationDecision)]
    public async Task<IActionResult> Nomination(ApprovedUserToRemoveViewModel model)
    {
        const string backLink = PagePath.NominationDecision;
        ViewBag.BackLinkToDisplay = backLink;

        var session = await _sessionManager.GetSessionAsync(HttpContext.Session) ?? new();

        if (model.NominationDecision == null)
        {
            ModelState.AddModelError(nameof(session.AddRemoveApprovedUserSession.NominationDecision), "NominateApproved.Decision.Error");
            return View(nameof(NominationDecision));
        }

        session.AddRemoveApprovedUserSession.NominationDecision = model.NominationDecision;
        _sessionManager.SaveSessionAsync(HttpContext.Session, session);

        if (session.AddRemoveApprovedUserSession.NominationDecision == true)
        {
            return RedirectToAction("ApprovedPersonListPage");
        }
        return RedirectToAction("ConfirmNominationDecision");
    }

    [HttpGet]
    [Route(PagePath.NominationDecisionConfirmation)]
    public async Task<IActionResult> ConfirmNominationDecision()
    {
        var session = await _sessionManager.GetSessionAsync(HttpContext.Session) ?? new();

        await AddCurrentPageAndSaveSession(session, PagePath.NominationDecisionConfirmation);
        SetBackLink(session, PagePath.NominationDecisionConfirmation);

        return View("NominateApprovedUserConfirmation", session.AddRemoveApprovedUserSession);

    }

    [HttpPost]
    [Route(PagePath.NominationDecisionConfirmation)]
    public async Task<IActionResult> Submit(ApprovedUserToRemoveViewModel model)
    {
        var session = await _sessionManager.GetSessionAsync(HttpContext.Session) ?? new JourneySession();
        if (model.ConnExternalId != Guid.Empty && model.OrganisationId != Guid.Empty)
        {
            session.AddRemoveApprovedUserSession.ExternalOrganisationId = model.OrganisationId;
            session.AddRemoveApprovedUserSession.ConnExternalId = model.ConnExternalId;
            session.AddRemoveApprovedUserSession.NominationDecision = model.NominationDecision;
        }

        var request = new RemoveApprovedUserRequest
        {
            RemovedConnectionExternalId = model.ConnExternalId,
            OrganisationId = model.OrganisationId,
            PromotedPersonExternalId = model.PromotedPersonExternalId
        };

        var response = await _facadeService.RemoveApprovedUser(request);
        session.AddRemoveApprovedUserSession.ResponseStatus = response;

        if (response == EndpointResponseStatus.Success)
        {
            //This is the nominate only flow (no removal)
            if (model.NominationDecision == null)
            {
                return await NominateOnly(session.AddRemoveApprovedUserSession);
            }

            //This is remove and nominate flow
            if (model.NominationDecision == true)
            {
                return await RemoveAndNominate(session.AddRemoveApprovedUserSession);
            }

            //This is the remove only flow (model.NominationDecision == false, ie. no nomination)
            return View("RemovedConfirmation", session.AddRemoveApprovedUserSession);
        }
        return RedirectToAction(PagePath.Error, "Error");
    }

    [HttpGet]
    [Route("[controller]/" + nameof(NominateOnly))]
    public async Task<IActionResult> NominateOnly(AddRemoveApprovedUserSession addRemoveApprovedUserSession)
    {
        var promotedApprovedUserModel = new RemovedNominatedUserViewModel()
        {
            PromotedUserName =
                $"{addRemoveApprovedUserSession.NewApprovedUser.FirstName} " +
                $"{addRemoveApprovedUserSession.NewApprovedUser.LastName}",
            OrganisationName = addRemoveApprovedUserSession.OrganisationName
        };
        return RedirectToAction("EmailNominatedApprovedPerson", promotedApprovedUserModel);
    }

    private async Task<IActionResult> RemoveAndNominate(AddRemoveApprovedUserSession addRemoveApprovedUserSession)
    {
        var promotedApprovedUserModel = new RemovedNominatedUserViewModel()
        {
            PromotedUserName =
                $"{addRemoveApprovedUserSession.NewApprovedUser.FirstName} " +
                $"{addRemoveApprovedUserSession.NewApprovedUser.LastName}",
            RemovedUserName = addRemoveApprovedUserSession.UserNameToRemove,
            OrganisationName = addRemoveApprovedUserSession.OrganisationName
        };
        return RedirectToAction("AccountPermissionsChanged", promotedApprovedUserModel);
    }


    [HttpGet]
    [Route(PagePath.EmailNominatedApprovedPerson)]
    public async Task<ActionResult> EmailNominatedApprovedPerson(RemovedNominatedUserViewModel model)
        => View("EmailSentToNominatedApprovedPerson", model);
    
    [HttpGet]
    [Route(PagePath.AccountPermissionsChanged)]
    public async Task<ActionResult> AccountPermissionsChanged(RemovedNominatedUserViewModel model)
        => View("AccountPermissionsHaveChanged", model);


    [HttpGet]
    [Route(PagePath.ApprovedPersonListPage)]
    public async Task<ActionResult> ApprovedPersonListPage()
    {
        var session = await _sessionManager.GetSessionAsync(HttpContext.Session) ?? new JourneySession();

        var results = await _facadeService.GetProducerOrganisationUsersByOrganisationExternalId(session.AddRemoveApprovedUserSession.ExternalOrganisationId);

        var model = new OrganisationUsersModel
        {
            ExternalOrganisationId = session.AddRemoveApprovedUserSession.ExternalOrganisationId,
            OrganisationUsers = results.Where(user => user.Email != session.AddRemoveApprovedUserSession.CurrentApprovedUserEmail).ToList(),
            NewApprovedUserId = session.AddRemoveApprovedUserSession.NewApprovedUser?.PersonExternalId
        };

        await AddCurrentPageAndSaveSession(session, PagePath.ApprovedPersonListPage);
        SetBackLink(session, PagePath.ApprovedPersonListPage);

        return View(model);
    }

    [HttpPost]
    [Route(PagePath.ApprovedPersonListPage)]
    public async Task<ActionResult> ApprovedPersonListPage(OrganisationUsersModel model)
    {
        var session = await _sessionManager.GetSessionAsync(HttpContext.Session) ?? new JourneySession();

        var results = await _facadeService.GetProducerOrganisationUsersByOrganisationExternalId(model.ExternalOrganisationId);

        if (ModelState.IsValid)
        {
            if (model.NewApprovedUserId == Guid.Empty)
            {
                session.InviteNewApprovedPersonSession = new InviteNewApprovedPersonSession();
                await AddCurrentPageAndSaveSession(session, PagePath.ApprovedPersonListPage);
                return RedirectToAction("EnterPersonName", "InviteNewApprovedPerson");
            }

            var selectedUser = results.Find(r => r.PersonExternalId == model.NewApprovedUserId);
            if (selectedUser != null)
            {
                session.AddRemoveApprovedUserSession.NewApprovedUser = selectedUser;
                _sessionManager.SaveSessionAsync(HttpContext.Session, session);

                return RedirectToAction("ConfirmNominationDecision", session.AddRemoveApprovedUserSession);
            }
        }

src/EPR.RegulatorService.Frontend.Web/Views/RemoveApprovedUser/AccountPermissionsHaveChanged.cshtml
@addTagHelper *, Microsoft.FeatureManagement.AspNetCore

@model EPR.RegulatorService.Frontend.Web.ViewModels.RemoveApprovedUser.RemovedNominatedUserViewModel;

<div class="govuk-width-container">
  <main class="govuk-main-wrapper govuk-main-wrapper--l" id="main-content" role="main">
    <div class="govuk-grid-row">
      <div class="govuk-grid-column-two-thirds">
        <div class="govuk-panel govuk-panel--confirmation">
          <h1 class="govuk-panel__title">
            @Localizer["Page.Panel"]
          </h1>
        </div>
        <p id="pageTitle" class="govuk-body">
          @Localizer["Page.RemoveAndNominate", Model.RemovedUserName, Model.OrganisationName, Model.PromotedUserName]
          </p>
        <h2 class="govuk-heading-m">@Localizer["Page.Heading"]</h2>

        <div class="govuk-inset-text">
          <p id="whenAccountIsCreated" class="govuk-body">
            @Localizer["Content.WhenAccountIsCreated", Model.PromotedUserName]
          </p>
          <p id="userDoesNotApply" class="govuk-body">
            @Localizer["Content.DoesNotApply", Model.PromotedUserName]
          </p>
        </div>
      </div>
    </div>

    <div class="govuk-grid-row">
      <div id="goToHomeLink" class="govuk-grid-column-full">
        @Html.ActionLink(@SharedLocalizer["Custom.GoToHome"],
          "LandingPage",
          "Home",
          null,
          new {@class = "govuk-body govuk-link govuk-link--no-visited-state"})
      </div>
    </div>
  </main>
</div>

src/EPR.RegulatorService.Frontend.Web/Views/RemoveApprovedUser/ApprovedPersonListPage.cshtml
@using EPR.RegulatorService.Frontend.Web.ViewModels.Shared.GovUK
@using EPR.RegulatorService.Frontend.Web.Extensions
@model EPR.RegulatorService.Frontend.Web.ViewModels.ApprovedPersonListPage.OrganisationUsersModel

@{
  ViewData["Title"] = @Localizer["Page.Title"];
  var errorsViewModel = new ErrorsViewModel(ViewData.ModelState.ToErrorDictionary(), Localizer);
  var radioButtonIndex = "";
}

<form action="@Url.Action("ApprovedPersonListPage", "RemoveApprovedUser")"
      enctype="application/x-www-form-urlencoded" method="POST">

  <div class="govuk-width-container">
    <main class="govuk-main-wrapper" id="main-content" role="main">
      <div class="govuk-grid-row">
        <div class="govuk-grid-column-full">

          @await Html.PartialAsync("Partials/Govuk/_ErrorSummary", errorsViewModel)
          <div class="govuk-form-group @(ViewData.ModelState.IsValid ? string.Empty : "govuk-form-group--error")">

            <fieldset class="govuk-fieldset">
              <legend class="govuk-fieldset__legend govuk-fieldset__legend--l">
                <h1 class="govuk-heading-xl govuk-!-margin-bottom-2">@Localizer["Page.Title"]</h1>
                <div class="govuk-hint" id="select-user-hint">@Localizer["Page.Title.Hint"]</div>
              </legend>

              @if (!ViewData.ModelState.IsValid)
              {
                  @await Html.PartialAsync("Partials/Govuk/_ErrorList", errorsViewModel)
                  <br/>
              }

              <div class="govuk-radios" data-module="govuk-radios">
                @foreach (var user in Model.OrganisationUsers
                  .Select((value, index) => new { Index = index, Value = value }))
                {
                  radioButtonIndex = user.Index == 0 ? "" : user.Index.ToString();

                  <div class="govuk-radios__item">
                    <input class="govuk-radios__input"
                           id="NewApprovedUserId@(radioButtonIndex)"
                           name="NewApprovedUserId"
                           aria-describedby="select-user-hint"
                           type="radio"
                           checked=@(Model.NewApprovedUserId == user.Value.PersonExternalId)
                           value=@user.Value.PersonExternalId>

                    <label class="govuk-label govuk-radios__label" for="NewApprovedUserId@(radioButtonIndex)">
                      <span>@user.Value.FirstName @user.Value.LastName</span><br/>
                      <span class="govuk-hint">@user.Value.Email</span>
                    </label>
                  </div>
                }

                @if (Model.OrganisationUsers.Any())
                {
                    radioButtonIndex = Model.OrganisationUsers.Count.ToString();
                }

                <div class="govuk-radios__item">
                  <input class="govuk-radios__input"
                         aria-describedby="select-user-hint"
                         id="NewApprovedUserId@(radioButtonIndex)"
                         name="NewApprovedUserId"
                         type="radio"
                         value=@Guid.Empty>
                  <label class="govuk-label govuk-radios__label"
                          for="NewApprovedUserId@(radioButtonIndex)">
                    <span>@Localizer["Someone.new"]</span>
                  </label>
                </div>
              </div>
            </fieldset>
          </div>

          <input type="hidden" asp-for="ExternalOrganisationId" value="@Model.ExternalOrganisationId" />
          <button class="govuk-button" data-module="govuk-button">@SharedLocalizer["Continue"]</button>
        </div>
      </div>
    </main>
  </div>
</form>

src/EPR.RegulatorService.Frontend.Web/Views/RemoveApprovedUser/Confirm.cshtml
@addTagHelper *, Microsoft.FeatureManagement.AspNetCore

@model EPR.RegulatorService.Frontend.Core.Sessions.AddRemoveApprovedUserSession

@{
  ViewData["Title"] = Localizer["Page.Title", Model.UserNameToRemove, Model.OrganisationName];
}

<form id="removeUserForm" action="@Url.Action("NominationDecision", "RemoveApprovedUser", Model)"
      enctype="application/x-www-form-urlencoded" method="GET">
  <div class="govuk-width-container">
    <main class="govuk-main-wrapper govuk-!-padding-top-4" id="main-content" role="main">
      <div class="govuk-grid-row">
        <div class="govuk-grid-column-full">
          <h1 id="pageTitle" class="govuk-heading-l govuk-!-margin-bottom-8">
            @Localizer["Page.Title", Model.UserNameToRemove, Model.OrganisationName]
          </h1>
          <div id="warningText" class="govuk-warning-text">
            <span class="govuk-warning-text__icon" aria-hidden="true">!</span>
            <span class="govuk-warning-text__text govuk-!-font-weight-regular">
              <span class="govuk-visually-hidden" style="font-weight: normal">Warning</span>
              @Localizer["Warning.Submit.Packaging"]
              <br/>
              <br/>
              @Localizer["Warning.Users"]
            </span>
          </div>
          <button id="continueButton" class="govuk-button" data-module="govuk-button" type="submit">
            @SharedLocalizer["Continue"]
          </button>
        </div>
      </div>
    </main>
  </div>
</form>

src/EPR.RegulatorService.Frontend.Web/Views/RemoveApprovedUser/EmailSentToNominatedApprovedPerson.cshtml
@addTagHelper *, Microsoft.FeatureManagement.AspNetCore

@model EPR.RegulatorService.Frontend.Web.ViewModels.RemoveApprovedUser.RemovedNominatedUserViewModel;

<div class="govuk-width-container">
  <main class="govuk-main-wrapper govuk-main-wrapper--l" id="main-content" role="main">
    <div class="govuk-grid-row">
      <div class="govuk-grid-column-two-thirds">
        <div class="govuk-panel govuk-panel--confirmation">
          <h1 class="govuk-panel__title">
            @Localizer["Page.Panel"]
          </h1>
        </div>
        <p id="pageTitle" class="govuk-body">
                    @Localizer["Page.CreateAccount", Model.PromotedUserName, Model.OrganisationName]
          </p>
        <h2 class="govuk-heading-m">@Localizer["Page.Heading"]</h2>

        <div class="govuk-inset-text">
          <p id="whenAccountIsCreated" class="govuk-body">
            @Localizer["Content.WhenAccountIsCreated", Model.PromotedUserName]
          </p>
          <p id="userDoesNotApply" class="govuk-body">
            @Localizer["Content.DoesNotApply", Model.PromotedUserName]
          </p>
        </div>
      </div>
    </div>

    <div class="govuk-grid-row">
      <div id="goToHomeLink" class="govuk-grid-column-full">
        @Html.ActionLink(@SharedLocalizer["Custom.GoToHome"],
          "LandingPage",
          "Home",
          null,
          new {@class = "govuk-body govuk-link govuk-link--no-visited-state"})
      </div>
    </div>
  </main>
</div>

src/EPR.RegulatorService.Frontend.Web/Views/RemoveApprovedUser/NominateApprovedUserConfirmation.cshtml
@addTagHelper *, Microsoft.FeatureManagement.AspNetCore

@model EPR.RegulatorService.Frontend.Core.Sessions.AddRemoveApprovedUserSession

@{
  ViewData["Title"] = @Localizer["Page.Title"];
}

<form id="removeUserForm" action="@Url.Action("Submit", "RemoveApprovedUser", Model)"
      enctype="application/x-www-form-urlencoded" method="post">
  <input id="hiddenConnExternalId" type="hidden" value=@Model.ConnExternalId name="ConnExternalId"/>
  <input id="hiddenOrganisationId" type="hidden" value=@Model.ExternalOrganisationId name="OrganisationId"/>
  <input id="hiddenPromotedPersonExternalId" type="hidden" value=@Model.NewApprovedUser?.PersonExternalId name="PromotedPersonExternalId"/>

  <div class="govuk-width-container">
    <main class="govuk-main-wrapper govuk-!-padding-top-4" id="main-content" role="main">
      <div class="govuk-grid-row">
        <div class="govuk-grid-column-full">
          <div class="govuk-form-group">
            <fieldset class="govuk-fieldset">
              <legend class="govuk-fieldset__legend govuk-fieldset__legend--l">
                <h1 id="pageTitle" class="govuk-fieldset__heading">
                  @Localizer["Page.Title"]
                </h1>
              </legend>
              <dl class="govuk-summary-list">
                @if (Model.NominationDecision != null)
                {
                  <div class="govuk-summary-list__row">
                    <dt id="userPrompt" class="govuk-summary-list__key">
                      @Localizer["Question.HasAnApprovedPersonBeenNominated"]
                    </dt>
                    <dd id="nominationDecision" class="govuk-summary-list__value">
                      @(Model.NominationDecision == true ? SharedLocalizer["Yes"] : SharedLocalizer["No"])
                    </dd>
                    <dd class="govuk-summary-list__actions">
                      <a id="changeButton" class="govuk-link" href="@Url.Action("NominationDecision", "RemoveApprovedUser")">
                        @SharedLocalizer["Change"]
                      </a>
                    </dd>
                  </div>
                }
                @if (Model.NominationDecision != false && Model.NewApprovedUser != null)
                {
                  <div class="govuk-summary-list__row">
                    <dt id="userPrompt" class="govuk-summary-list__key">
                      @Localizer["Question.Name"]
                    </dt>
                    <dd id="nominationDecision" class="govuk-summary-list__value">
                      @Model.NewApprovedUser.FirstName @Model.NewApprovedUser.LastName <br/>
                      @Model.NewApprovedUser.Email
                    </dd>
                    <dd class="govuk-summary-list__actions">
                      <a id="changeButton" class="govuk-link" href="@Url.Action("ApprovedPersonListPage", "RemoveApprovedUser")">
                        @SharedLocalizer["Change"]
                      </a>
                    </dd>
                  </div>
                }
              </dl>
            </fieldset>
          </div>
          <button id="confirmButton" class="govuk-button" data-module="govuk-button" type="submit">
            @SharedLocalizer["Confirm"]
          </button>
        </div>
      </div>
    </main>
  </div>
</form>

src/EPR.RegulatorService.Frontend.Web/Views/RemoveApprovedUser/NominationDecision.cshtml
@addTagHelper *, Microsoft.FeatureManagement.AspNetCore

@using EPR.RegulatorService.Frontend.Web.ViewModels.Shared.GovUK
@using EPR.RegulatorService.Frontend.Web.Extensions
@model EPR.RegulatorService.Frontend.Core.Sessions.AddRemoveApprovedUserSession

@{
  ViewData["Title"] = @Localizer["Page.Title"];
  var errorsViewModel = new ErrorsViewModel(ViewData.ModelState.ToErrorDictionary(), Localizer);
}

<form action="@Url.Action("Nomination", "RemoveApprovedUser", Model)"
      enctype="application/x-www-form-urlencoded" method="POST">
  @Html.AntiForgeryToken()

  <div class="govuk-width-container">
    <main class="govuk-main-wrapper govuk-!-padding-top-4" id="main-content" role="main">
      <div class="govuk-grid-row">
        <div id="errorSummary" class="govuk-grid-column-full">
          @if (errorsViewModel.HasErrorKey(nameof(Model.NominationDecision)))
          {
            @await Html.PartialAsync("Partials/Govuk/_ErrorSummary", errorsViewModel)
          }
          <div class="govuk-form-group">
            <fieldset class="govuk-fieldset">
              <div class="govuk-form-group@(errorsViewModel.HasErrorKey(nameof(Model.NominationDecision)) ? " govuk-form-group--error" : "")">
                @await Html.PartialAsync("Partials/Govuk/_FormItemError", errorsViewModel[nameof(Model.NominationDecision)])
                <legend class="govuk-fieldset__legend govuk-fieldset__legend--l">
                  <h1 id="pageTitle"class="govuk-fieldset__heading">
                    @Localizer["Page.Title"]
                  </h1>
                </legend>
                <div class="govuk-radios" data-module="govuk-radios">
                  <div class="govuk-radios__item">
                    <input class="govuk-radios__input"
                           id="nominationDecisionYes"
                           name="nominationDecision"
                           type="radio"
                           aria-labelledby="radio-label-accepted-true"
                           gov-for="NominationDecision"
                           gov-first-option="true"
                           checked=@(Model.NominationDecision == true)
                           gov-value="true">
                    <label class="govuk-label govuk-radios__label"
                           for="nominationDecisionYes"
                           id="radio-label-accepted-true"
                           gov-for="NominationDecision"
                           gov-first-option="true"
                           gov-value="true">
                      @SharedLocalizer["Yes"]
                    </label>
                  </div>
                  <div class="govuk-radios__item">
                    <input class="govuk-radios__input"
                           id="nominationDecisionNo"
                           name="nominationDecision"
                           type="radio"
                           aria-labelledby="radio-label-accepted-false"
                           value="false"
                           checked=@(Model.NominationDecision == false)
                           gov-for="NominationDecision"
                           gov-first-option="false"
                           gov-value="false">
                    <label id="radio-label-accepted-false"
                           class="govuk-label govuk-radios__label"
                           for="nominationDecisionNo"
                           gov-for="NominationDecision"
                           gov-first-option="false"
                           gov-value="false">
                      @SharedLocalizer["No"]
                    </label>
                  </div>
                </div>
              </div>
            </fieldset>
          </div>
          <button id="continueButton" class="govuk-button" data-module="govuk-button" type="submit">
            @SharedLocalizer["Continue"]
          </button>
        </div>
      </div>
    </main>
  </div>
</form>

src/EPR.RegulatorService.Frontend.Web/Views/RemoveApprovedUser/RemovedConfirmation.cshtml
@addTagHelper *, Microsoft.FeatureManagement.AspNetCore

@model EPR.RegulatorService.Frontend.Core.Sessions.AddRemoveApprovedUserSession

<div class="govuk-width-container">
  <main class="govuk-main-wrapper govuk-main-wrapper--l" id="main-content" role="main">
    <div class="govuk-grid-row">
      <div class="govuk-grid-column-two-thirds">
        <div class="govuk-panel govuk-panel--confirmation">
          <h1 class="govuk-panel__title">
            @Localizer["Page.Panel"]
          </h1>
        </div>
        <p id="pageTitle" class="govuk-body">
          @Localizer["Page.Title", Model.UserNameToDelete, Model.OrganisationName]
          </p>
        <h2 class="govuk-heading-m">@Localizer["Page.Heading"]</h2>

        <div class="govuk-inset-text">
          <p id="cannotSubmitConfirmation" class="govuk-body">
            @Localizer["Confirmation.CannotSubmit.PackagingData"]
          </p>
          <p id="nominateApprovedUserConfirmation" class="govuk-body">
            @Localizer["Confirmation.Nominate.ApprovedUser"]
          </p>
        </div>
      </div>
    </div>

    <div class="govuk-grid-row">
      <div id="goToHomeLink" class="govuk-grid-column-full">
        @Html.ActionLink(@SharedLocalizer["Custom.GoToHome"],
          "LandingPage",
          "Home",
          null,
          new {@class = "govuk-body govuk-link govuk-link--no-visited-state"})
      </div>
    </div>
  </main>
</div>