src/EPR.RegulatorService.Frontend.Web/ViewModels/Cookies/CookieBannerModel.cs
using System.Diagnostics.CodeAnalysis;

namespace EPR.RegulatorService.Frontend.Web.ViewModels.Cookies;

[ExcludeFromCodeCoverage]
public class CookieBannerModel
{
    public bool ShowBanner { get; set; }

    public bool ShowAcknowledgement { get; set; }

    public bool AcceptAnalytics { get; set; }

    public string? ReturnUrl { get; set; }

    public string CurrentPage { get; set; }
}

src/EPR.RegulatorService.Frontend.Web/ViewModels/Cookies/CookieDetailViewModel.cs
using System.Diagnostics.CodeAnalysis;

namespace EPR.RegulatorService.Frontend.Web.ViewModels.Cookies;

[ExcludeFromCodeCoverage]
public class CookieDetailViewModel
{
    public bool CookiesAccepted { get; set; }

    public bool ShowAcknowledgement { get; set; }

    public string B2CCookieName { get; set; }
    
    public string CookiePolicyCookieName { get; set; }

    public string SessionCookieName { get; set; }

    public string AntiForgeryCookieName { get; set; }

    public string TsCookieName { get; set; }

    public string AuthenticationCookieName { get; set; }

    public string TempDataCookieName { get; set; }

    public string GoogleAnalyticsDefaultCookieName { get; set; }

    public string GoogleAnalyticsAdditionalCookieName { get; set; }

    public string? ReturnUrl { get; set; }
}

src/EPR.RegulatorService.Frontend.Web/Controllers/Cookies/CookiesController.cs
using EPR.RegulatorService.Frontend.Web.Configs;
using EPR.RegulatorService.Frontend.Web.Constants;
using EPR.RegulatorService.Frontend.Web.Cookies;
using EPR.RegulatorService.Frontend.Web.Extensions;
using EPR.RegulatorService.Frontend.Web.ViewModels.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;

namespace EPR.RegulatorService.Frontend.Web.Controllers.Cookies;

[AllowAnonymous]
[Route("[controller]/[action]")]
public class CookiesController : Controller
{
    private readonly ICookieService _cookieService;
    private readonly EprCookieOptions _eprCookieOptions;
    private readonly AnalyticsOptions _googleAnalyticsOptions;

    public CookiesController(
        ICookieService cookieService,
        IOptions<EprCookieOptions> eprCookieOptions,
        IOptions<AnalyticsOptions> googleAnalyticsOptions)
    {
        _cookieService = cookieService;
        _eprCookieOptions = eprCookieOptions.Value;
        _googleAnalyticsOptions = googleAnalyticsOptions.Value;
    }

    [HttpPost]
    [Route(PagePath.UpdateCookieAcceptance)]
    public LocalRedirectResult UpdateAcceptance(string returnUrl, string cookies)
    {
        _cookieService.SetCookieAcceptance(cookies == CookieAcceptance.Accept, Request.Cookies, Response.Cookies);
        TempData[CookieAcceptance.CookieAcknowledgement] = cookies;

        return LocalRedirect(returnUrl);
    }

    [HttpPost]
    [Route(PagePath.AcknowledgeCookieAcceptance)]
    public LocalRedirectResult AcknowledgeAcceptance(string returnUrl)
    {
        if (!Url.IsLocalUrl(returnUrl))
        {
            returnUrl = Url.HomePath();
        }

        return LocalRedirect(returnUrl);
    }

    [Route(PagePath.Cookies)]
    public IActionResult Detail(string returnUrl)
    {
        var hasUserAcceptedCookies = _cookieService.HasUserAcceptedCookies(Request.Cookies);

        if (!Url.IsLocalUrl(returnUrl))
        {
            returnUrl = Url.HomePath();
        }

        var returnPath = string.IsNullOrEmpty(Request.Path.Value) ? Url.HomePath() : Request.Path.Value;

        var cookieViewModel = new CookieDetailViewModel
        {
            SessionCookieName = _eprCookieOptions.SessionCookieName,
            B2CCookieName = _eprCookieOptions.B2CCookieName,
            CookiePolicyCookieName = _eprCookieOptions.CookiePolicyCookieName,
            AntiForgeryCookieName = _eprCookieOptions.AntiForgeryCookieName,
            GoogleAnalyticsDefaultCookieName = _googleAnalyticsOptions.DefaultCookieName,
            GoogleAnalyticsAdditionalCookieName = _googleAnalyticsOptions.AdditionalCookieName,
            AuthenticationCookieName= _eprCookieOptions.AuthenticationCookieName,
            TsCookieName= _eprCookieOptions.TsCookieName,
            TempDataCookieName= _eprCookieOptions.TempDataCookie,
            CookiesAccepted = hasUserAcceptedCookies,
            ReturnUrl = $"~{returnPath}{Request.QueryString}",
            ShowAcknowledgement = TempData[CookieAcceptance.CookieAcknowledgement] != null,
        };
        
        ViewBag.BackLinkToDisplay = Url.Content(returnUrl);
        ViewBag.CurrentPage = returnUrl;
        
        return View(cookieViewModel);
    }
}

src/EPR.RegulatorService.Frontend.Web/Views/Cookies/Detail.cshtml
@using EPR.RegulatorService.Frontend.Web.ViewModels.Cookies
@using EPR.RegulatorService.Frontend.Web.Constants
@model CookieDetailViewModel

@{
    ViewData["Title"] = @Localizer["Detail.Title"];
}

<div class="govuk-width-container">
    <main class="govuk-main-wrapper govuk-!-padding-top-4" id="main-content" role="main">
        <div class="govuk-grid-row">
            <div class="govuk-grid-column-two-thirds">
                @if (Model.ShowAcknowledgement)
                {
                    <div class="govuk-notification-banner govuk-notification-banner--success" role="alert" aria-labelledby="govuk-notification-banner-title" data-module="govuk-notification-banner">
                        <div class="govuk-notification-banner__header">
                            <h2 class="govuk-notification-banner__title" id="govuk-notification-banner-title">
                                @Localizer["Detail.Success"]
                            </h2>
                        </div>
                        <div class="govuk-notification-banner__content">
                            <p class="govuk-notification-banner__heading">
                                @Localizer["Detail.SetCookiePreferences"]
                            </p>
                        </div>
                    </div>
                }
                <h1 class="govuk-heading-l  govuk-!-margin-bottom-4">@Localizer["Detail.Title"]</h1>
                <p class="govuk-body">@Localizer["Detail.CookieDescription1"]</p>
                <p class="govuk-body">@Localizer["Detail.CookieDescription2"]</p>
                <h2 class="govuk-heading-m govuk-!-margin-top-2">@Localizer["Detail.EssentialCookies"]</h2>
                <p class="govuk-body">@Localizer["Detail.EssentialCookiesDescription"]</p>
                <table class="cookies-table govuk-table govuk-!-margin-bottom-4">
                    <caption class="govuk-table__caption govuk-!-margin-bottom-4">@Localizer["Detail.EssentialCookiesWeUse"]</caption>
                    <thead class="govuk-table__head">
                    <tr class="govuk-table__row">
                        <th scope="col" class="govuk-table__header">@Localizer["Detail.Name"]</th>
                        <th scope="col" class="govuk-table__header">@Localizer["Detail.Purpose"]</th>
                        <th scope="col" class="govuk-table__header">@Localizer["Detail.Expires"]</th>
                    </tr>
                    </thead>
                    <tbody class="govuk-table__body">
                    <tr class="govuk-table__row">
                        <th scope="row" class="govuk-table__header">@Model.B2CCookieName</th>
                        <td class="govuk-table__cell">@Localizer["Detail.RegistrationAuthenticationCookiePurpose"]</td>
                        <td class="govuk-table__cell">@Localizer["Detail.EssentialCookieExpiresSession"]</td>
                    </tr>
                    <tr class="govuk-table__row">
                        <th scope="row" class="govuk-table__header">@Model.TsCookieName</th>
                        <td class="govuk-table__cell">@Localizer["Detail.EssentialCookiePurpose6"]</td>
                        <td class="govuk-table__cell">@Localizer["Detail.EssentialCookieExpiresSession"]</td>
                    </tr>
                    <tr class="govuk-table__row">
                        <th scope="row" class="govuk-table__header">@Model.SessionCookieName</th>
                        <td class="govuk-table__cell">@Localizer["Detail.EssentialCookiePurpose2"]</td>
                        <td class="govuk-table__cell">@Localizer["Detail.EssentialCookieExpiresSession"]</td>
                    </tr>
                    <tr class="govuk-table__row">
                      <th scope="row" class="govuk-table__header">@Model.AuthenticationCookieName</th>
                      <td class="govuk-table__cell">@Localizer["Detail.EssentialCookiePurpose4"]</td>
                      <td class="govuk-table__cell">@Localizer["Detail.EssentialCookieExpiresSession"]</td>
                    </tr>
                    <tr class="govuk-table__row">
                      <th scope="row" class="govuk-table__header">@Model.AntiForgeryCookieName</th>
                      <td class="govuk-table__cell">@Localizer["Detail.EssentialCookiePurpose3"]</td>
                      <td class="govuk-table__cell">@Localizer["Detail.EssentialCookieExpiresSession"]</td>
                    </tr>
                    <tr class="govuk-table__row">
                      <th scope="row" class="govuk-table__header">@Model.CookiePolicyCookieName</th>
                      <td class="govuk-table__cell">@Localizer["Detail.EssentialCookiePurpose1"]</td>
                      <td class="govuk-table__cell">@Localizer["Detail.EssentialCookieExpires1"]</td>
                    </tr>
                    <tr class="govuk-table__row">
                      <th scope="row" class="govuk-table__header">@Model.TempDataCookieName</th>
                      <td class="govuk-table__cell">@Localizer["Detail.EssentialCookiePurpose5"]</td>
                      <td class="govuk-table__cell">@Localizer["Detail.EssentialCookieExpiresSession"]</td>
                    </tr>
                    </tbody>
                </table>
                <h2 class="govuk-heading-m govuk-!-margin-top-8">@Localizer["Detail.AnalyticsCookies"]</h2>
                <p class="govuk-body">@Localizer["Detail.AnalyticalCookiesDescription1"]</p>
                <p class="govuk-body">@Localizer["Detail.AnalyticalCookiesDescription2"]</p>
                <p class="govuk-body">@Localizer["Detail.AnalyticalCookiesDescription3"]</p>
                <ul class="govuk-list govuk-list--bullet">
                    <li>@Localizer["Detail.AnalyticalCookiesPoint1"]</li>
                    <li>@Localizer["Detail.AnalyticalCookiesPoint2"]</li>
                    <li>@Localizer["Detail.AnalyticalCookiesPoint3"]</li>
                    <li>@Localizer["Detail.AnalyticalCookiesPoint4"]</li>
                    <li>@Localizer["Detail.AnalyticalCookiesPoint5"]</li>
                </ul>
                <table class="cookies-table govuk-table">
                    <caption class="govuk-table__caption govuk-!-margin-bottom-4 govuk-!-margin-top-4">@Localizer["Detail.AnalyticsCookiesWeUse"]</caption>
                    <thead class="govuk-table__head">
                    <tr class="govuk-table__row">
                        <th scope="col" class="govuk-table__header">@Localizer["Detail.Name"]</th>
                        <th scope="col" class="govuk-table__header">@Localizer["Detail.Purpose"]</th>
                        <th scope="col" class="govuk-table__header">@Localizer["Detail.Expires"]</th>
                    </tr>
                    </thead>
                    <tbody class="govuk-table__body">
                        <tr class="govuk-table__row">
                            <th scope="row" class="govuk-table__header">@Model.GoogleAnalyticsDefaultCookieName</th>
                            <td class="govuk-table__cell">@Localizer["Detail.AnalyticsCookiePurpose1"]</td>
                            <td class="govuk-table__cell">@Localizer["Detail.AnalyticsCookieExpires1"]</td>
                        </tr>
                        <tr class="govuk-table__row">
                            <th scope="row" class="govuk-table__header">@Model.GoogleAnalyticsAdditionalCookieName</th>
                            <td class="govuk-table__cell">@Localizer["Detail.AnalyticsCookiePurpose2"]</td>
                            <td class="govuk-table__cell">@Localizer["Detail.AnalyticsCookieExpires2"]</td>
                        </tr>
                    </tbody>
                </table>
                <form method="POST" asp-controller="Cookies" asp-action="UpdateAcceptance" asp-route-returnUrl="@Model.ReturnUrl">
                    <div class="govuk-form-group">
                        <fieldset class="govuk-fieldset js-cookies-page-form-fieldset" id="analytics">
                            <legend class="govuk-fieldset__legend govuk-fieldset__legend--s">
                                @Localizer["Detail.Accept"]
                            </legend>
                            <div class="govuk-radios" data-module="govuk-radios">
                                <div class="govuk-radios__item">
                                    <input class="govuk-radios__input" id="radio-analytics" name="cookies" @(Model.CookiesAccepted ? "checked='checked'" : "") type="radio" value="@CookieAcceptance.Accept">
                                    <label class="govuk-label govuk-radios__label" for="radio-analytics">
                                        @Localizer["Detail.Yes"]
                                    </label>
                                </div>
                                <div class="govuk-radios__item">
                                    <input class="govuk-radios__input" id="radio-analytics-2" name="cookies" @(Model.CookiesAccepted ? "" : "checked='checked'") type="radio" value="@CookieAcceptance.Reject">
                                    <label class="govuk-label govuk-radios__label" for="radio-analytics-2">
                                        @Localizer["Detail.No"]
                                    </label>
                                </div>
                            </div>
                        </fieldset>
                    </div>
                    <button class="govuk-button js-cookies-form-button" type="submit" data-module="govuk-button" hidden="true">
                        @Localizer["Detail.SaveCookieSettings"]
                    </button>
                </form>
            </div>
        </div>
    </main>
</div>