src/EPR.RegulatorService.Frontend.Web/ViewModels/RegulatorEnrolment/FullNameViewModel.cs
namespace EPR.RegulatorService.Frontend.Web.ViewModels.RegulatorEnrolment
{
    using System.ComponentModel.DataAnnotations;

    public class FullNameViewModel
    {
        [Required(ErrorMessage = "FirstName.RequiredError")]
        [StringLength(50, ErrorMessage = "FirstName.LengthError")]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "LastName.RequiredError")]
        [StringLength(50, ErrorMessage = "LastName.LengthError")]
        public string LastName { get; set; }

        public string? Token { get; set; }
    }
}

src/EPR.RegulatorService.Frontend.Web/Controllers/RegulatorEnrolment/RegulatorEnrolmentController.cs
namespace EPR.RegulatorService.Frontend.Web.Controllers.RegulatorEnrolment
{
    using System.Security.Claims;

    using Constants;

    using Core.Models;
    using Core.Services;
    using Core.Sessions;

    using Extensions;

    using Microsoft.AspNetCore.Mvc;
    using Microsoft.Identity.Web;

    using ViewModels.RegulatorEnrolment;

    [Route("")]
    public class RegulatorEnrolmentController : Controller
    {
        private readonly ILogger<RegulatorEnrolmentController> _logger;
        private readonly IFacadeService _facadeService;

        public RegulatorEnrolmentController(ILogger<RegulatorEnrolmentController> logger,
            IFacadeService facadeService)
        {
            _logger = logger;
            _facadeService = facadeService;
        }

        [HttpGet]
        [Route(PagePath.FullName)]
        public async Task<ActionResult> FullName(string? token)
        {
            var session = new JourneySession
            {
                UserData = HttpContext.User.GetInvitedUserData()
            };

            if (string.IsNullOrEmpty(token))
            {
                _logger.InvitedTokenWasNotProvided(session.UserData.Id);

                return RedirectToAction(PagePath.Error, "Error");
            }

            session.UserData.InviteToken = token;

            await ClaimsExtensions.UpdateUserDataClaimsAndSignInAsync(HttpContext, session.UserData);

            ViewBag.CurrentPage = $"{HttpContext.Request.PathBase}{HttpContext.Request.Path}?{nameof(token)}={token}";

            return View(new FullNameViewModel { Token = token });
        }

        [HttpPost]
        [Route(PagePath.FullName)]
        public async Task<ActionResult> FullName(FullNameViewModel model)
        {
            ViewBag.CurrentPage = $"{HttpContext.Request.PathBase}{HttpContext.Request.Path}?token={HttpContext.User.GetUserData().InviteToken}";

            if (ModelState.IsValid)
            {
                var session = new JourneySession
                {
                    UserData = HttpContext.User.GetUserData()
                };

                var request = new EnrolInvitedUserRequest
                {
                    InviteToken = session.UserData.InviteToken!,
                    FirstName = model.FirstName.Trim(),
                    LastName = model.LastName.Trim(),
                    Email = HttpContext.User.Claims.First(c => c.Type == ClaimTypes.Email).Value,
                    UserId = Guid.Parse(HttpContext.User.Claims.Single(claim => claim.Type == ClaimConstants.ObjectId).Value)
                };

                var result = await _facadeService.EnrolInvitedUser(request);

                if (result == EndpointResponseStatus.Success)
                {
                    _logger.EnrolmentForInvitedUserSuccessful(request.UserId);

                    session.UserData.FirstName = request.FirstName;
                    session.UserData.LastName = request.LastName;

                    await ClaimsExtensions.UpdateUserDataClaimsAndSignInAsync(HttpContext, session.UserData);

                    _logger.UserDataUpdated(request.UserId);

                    return RedirectToAction(PagePath.LandingPage, "Home");
                }

                _logger.EnrolmentForInvitedUserFailed(request.UserId);

                ModelState.AddModelError("Error", "Unable to enrol invited user");
            }

            return View(model);
        }
    }
}

src/EPR.RegulatorService.Frontend.Web/Views/RegulatorEnrolment/FullName.cshtml
@using EPR.RegulatorService.Frontend.Web.ViewModels.RegulatorEnrolment;
@using EPR.RegulatorService.Frontend.Web.ViewModels.Shared.GovUK
@using EPR.RegulatorService.Frontend.Web.Extensions

@model FullNameViewModel

@{
    ViewData["Title"] = Localizer["Page.Title"];
    var errorsViewModel = new ErrorsViewModel(ViewData.ModelState.ToErrorDictionary(), Localizer);
    const string errorClass = "govuk-input--error";
}

<form action="@Url.Action("FullName", "RegulatorEnrolment")?token=@Model.Token"
  enctype="multipart/form-data" method="POST">

    <div class="govuk-width-container">
        <main class="govuk-main-wrapper" id="main-content" role="main">
            <div class="govuk-grid-row">
                <div class="govuk-grid-column-full">

                    @if (!ViewData.ModelState.IsValid)
                    {
                        @await Html.PartialAsync("Partials/Govuk/_ErrorSummary", errorsViewModel)
                    }

                    <h1 class="govuk-heading-l">
                        @Localizer["Page.Title"]
                    </h1>
                    <div class="govuk-form-group">                        
                         <div class="govuk-form-group@(errorsViewModel.HasErrorKey(nameof(Model.FirstName)) ? " govuk-form-group--error" : "")"> 
                            <label class="govuk-label" asp-for="FirstName">
                                @Localizer["FirstName.Label"]
                            </label>

                            @await Html.PartialAsync("Partials/Govuk/_FormItemError", errorsViewModel[nameof(Model.FirstName)])
                            <input class="govuk-input govuk-!-width-two-thirds @Html.Raw(errorsViewModel.HasErrorKey(nameof(Model.FirstName))?errorClass:"")"
                                   type="text"
                                   gov-for="FirstName"
                                   gov-value="@Model.FirstName">
                        </div>
                        <div class="govuk-form-group@(errorsViewModel.HasErrorKey(nameof(Model.LastName)) ? " govuk-form-group--error" : "")">
                            <label class="govuk-label" asp-for="LastName">
                                @Localizer["LastName.Label"]
                            </label>

                            @await Html.PartialAsync("Partials/Govuk/_FormItemError", errorsViewModel[nameof(Model.LastName)])                            
                            <input class="govuk-input govuk-!-width-two-thirds @Html.Raw(errorsViewModel.HasErrorKey(nameof(Model.LastName))?errorClass:"")"
                                   type="text"
                                   gov-for="LastName"
                                   gov-value="@Model.LastName">
                        </div>
                    </div>
                    <button class="govuk-button" data-module="govuk-button" type="submit">
                        @SharedLocalizer["Continue"]
                    </button>
                </div>
            </div>
        </main>
    </div>
</form>